### PR TITLE
Fix epoch calculation when restoring snapshot in ignite

### LINKED ISSUE #12: Resumption from snapshot taken in the middle of the epoch
It seems that, if training is resumed from snapshot taken in the middle of the epoch, the rest of iterations of the epoch is not executed.

In the following example, I expect `ITERATION_COMPLETED` is printed 9 times after resumption but none is printed.

```python
import torch
import torch.nn.functional as F
import ignite
import ignite.contrib.handlers
from chainer.training import extensions
import chainer_pytorch_migration as cpm
import chainer_pytorch_migration.ignite


device = torch.device('cpu')

model = torch.nn.Linear(3, 1).to(device)

X = torch.randn(100, 3)
y = torch.randint(high=1, size=(100,)).to(torch.int64)
dataset = torch.utils.data.TensorDataset(X, y)


def create_trainer():
    optimizer = torch.optim.Adam(model.parameters())
    trainer = ignite.engine.create_supervised_trainer(
        model, optimizer, F.nll_loss, device=device)

    @trainer.on(ignite.engine.Events.ITERATION_COMPLETED)
    def print_ITERATION_COMPLETED(engine):
        print("ITERATION_COMPLETED", flush=True)

    optimizer.target = model
    trainer.out = "result"
    snapshot = extensions.snapshot(filename='snapshot_iteration-{.updater.iteration}')
    cpm.ignite.add_trainer_extension(trainer, optimizer, snapshot, trigger=(1, 'iteration'))

    return trainer, optimizer


trainer, optimizer = create_trainer()
train_loader = torch.utils.data.DataLoader(dataset, shuffle=True, batch_size=10)
trainer.run(train_loader, max_epochs=1)

trainer, optimizer = create_trainer()
cpm.ignite.load_chainer_snapshot(trainer, optimizer, "result/snapshot_iteration-1")
print("resumed", flush=True)
train_loader = torch.utils.data.DataLoader(dataset, shuffle=True, batch_size=10)
trainer.run(train_loader, max_epochs=1)
```

```
$ python test_resume.py
ITERATION_COMPLETED
ITERATION_COMPLETED
ITERATION_COMPLETED
ITERATION_COMPLETED
ITERATION_COMPLETED
ITERATION_COMPLETED
ITERATION_COMPLETED
ITERATION_COMPLETED
ITERATION_COMPLETED
ITERATION_COMPLETED
resumed
```

### PR DESCRIPTION
**Pull request by emcastillo**
Closes #12 
Epoch is increased in ignite engine state after the first iteration, causing issues when restoring the snapshot.
ignite calculates the epoch internally when restoring the status using just the iteration count and the epoch size. This PR mimics that

### CODE REVIEW

**Comment by msakai** [comment]
When I ran a program #12 on this branch, I encountered the following error.

```
Traceback (most recent call last):
  File "test_resume.py", line 38, in <module>
    trainer.run(train_loader, max_epochs=2)
  File "/Users/sakai/src/chainer-pytorch-migration/chainer_pytorch_migration/ignite/extensions.py", line 294, in pre_run
    Engine.run(self.engine, data, max_epochs)
  File "/Users/sakai/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/ignite/engine/engine.py", line 446, in run
    self._handle_exception(e)
  File "/Users/sakai/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/ignite/engine/engine.py", line 410, in _handle_exception
    raise e
  File "/Users/sakai/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/ignite/engine/engine.py", line 433, in run
    hours, mins, secs = self._run_once_on_dataset()
  File "/Users/sakai/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/ignite/engine/engine.py", line 399, in _run_once_on_dataset
    self._handle_exception(e)
  File "/Users/sakai/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/ignite/engine/engine.py", line 410, in _handle_exception
    raise e
  File "/Users/sakai/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/ignite/engine/engine.py", line 392, in _run_once_on_dataset
    self._fire_event(Events.ITERATION_COMPLETED)
  File "/Users/sakai/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/ignite/engine/engine.py", line 345, in _fire_event
    func(self, *(event_args + args), **kwargs)
  File "/Users/sakai/src/chainer-pytorch-migration/chainer_pytorch_migration/ignite/extensions.py", line 247, in run_extensions_on_iter
    self.run_extensions()
  File "/Users/sakai/src/chainer-pytorch-migration/chainer_pytorch_migration/ignite/extensions.py", line 281, in run_extensions
    entry.extension(self)
  File "/Users/sakai/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/chainer/training/extensions/_snapshot.py", line 407, in __call__
    self._make_snapshot(trainer)
  File "/Users/sakai/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/chainer/training/extensions/_snapshot.py", line 411, in _make_snapshot
    serialized_target = npz.serialize(target)
  File "/Users/sakai/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/chainer/serializers/npz.py", line 80, in serialize
    s.save(obj)
  File "/Users/sakai/.pyenv/versions/miniconda3-4.3.30/lib/python3.6/site-packages/chainer/serializer.py", line 67, in save
    obj.serialize(self)
  File "/Users/sakai/src/chainer-pytorch-migration/chainer_pytorch_migration/ignite/extensions.py", line 305, in serialize
    self.updater.serialize(serializer['updater'], state['updater'])
  File "/Users/sakai/src/chainer-pytorch-migration/chainer_pytorch_migration/ignite/extensions.py", line 174, in serialize
    state['epoch_length'] = self.engine.state.epoch_length
AttributeError: 'State' object has no attribute 'epoch_length'
```

It seems that `epoch_length` is introduced in https://github.com/pytorch/ignite/pull/640 and is available only on `pytorch-ignite >=0.3.0`. After I upgraded `pytorch-ignite` from 0.2.1 to 0.3.0, it worked fine. It might be friendly to warn about `pytorch-ignite` version or to document required version.

**Comment by emcastillo** [comment]
Yes, lets update documents.

**Comment by niboshi** [comment]
@emcastillo Let's check the ignite version in `ignite/__init__.py` and raise and error.

**Comment by emcastillo** [comment]
PTAL!

File: chainer_pytorch_migration/ignite/__init__.py [hunk 1]
```diff
@@ -1,2 +1,15 @@
+from packaging import version
```
Comment (niboshi) [inline chainer_pytorch_migration/ignite/__init__.py]: `packaging` is not a standard module. How about parsing manually?
I think it should be enough to parse up to the minor version and it's unlikely each component may contain non-digit characters.

File: chainer_pytorch_migration/ignite/__init__.py [hunk 2]
```diff
@@ -1,2 +1,15 @@
...
 from .extensions import add_trainer_extension, load_chainer_snapshot  # NOQA
 from .collate import collate_to_array  # NOQA
+
+
+class IgniteVersionError(Exception):
+    pass
+
+
+if version.parse(ignite.__version__) < version.parse('0.3.0'):
+    raise IgniteVersionError('Ignite version found {}. '
```
Comment (niboshi) [inline chainer_pytorch_migration/ignite/__init__.py]: Do you need a dedicated error type? How about `ImportError`?

File: chainer_pytorch_migration/ignite/__init__.py (hunk 1 above)
Comment (emcastillo) [reply chainer_pytorch_migration/ignite/__init__.py]: Ok, I am comparing now only the second component of the version string.

**Comment by niboshi** [comment]
Oh, please compare the major version too.

**Comment by emcastillo** [comment]
Done!

File: chainer_pytorch_migration/ignite/__init__.py [hunk 3]
```diff
@@ -1,2 +1,13 @@
+import ignite
+
 from .extensions import add_trainer_extension, load_chainer_snapshot  # NOQA
 from .collate import collate_to_array  # NOQA
+
+
+def _get_version(version):
+    return int(version.split('.')[:2])
```
Comment (niboshi) [inline chainer_pytorch_migration/ignite/__init__.py]: I think you should leave a comment that it intentionally compares only up to the minor version.
Otherwise someone could rewrite 2 to 3.

**Comment by niboshi** [comment]
Please write a test, too.

**Comment by emcastillo** [comment]
Added tests for both, version checking and the actual snapshot load.
Will change other snapshot tests to use TempDirectory in another PR.

File: tests/test_ignite.py [hunk 4]
```diff
@@ -0,0 +1,11 @@
+import chainer_pytorch_migration.ignite
+
+
+def test_version_comparisson():
+    version_fnct = chainer_pytorch_migration.ignite._get_version
+    assert version_fnct('0.0.0') < version_fnct('0.3.0')
```
Comment (niboshi) [inline tests/test_ignite.py]: How about testing like `assert version_fnct('0.0.0') == [0, 0]` but I'm not sure this function needs a test.

Comment (emcastillo) [reply tests/test_ignite.py]: Fixed!
I also changed the version function to use a regular expression and added some invalid case tests too. But yeah, I think that testing this may be a bit overkill

File: tests/test_ignite.py [hunk 5]
```diff
@@ -0,0 +1,31 @@
...
+    assert version_fnct('0.10.0') == [0, 10]
+    # This is because we only compare up to the minor
+    assert version_fnct('0.3.0') == [0, 3]
+    assert version_fnct('0.3.1a') == [0, 3]
+
+
+def test_invalid_version():
+    version_fnct = chainer_pytorch_migration.ignite._get_version
+    with pytest.raises(ValueError):
+        version_fnct('0.3a.0')
```
Comment (niboshi) [inline tests/test_ignite.py]: Why is this invalid?

Comment (emcastillo) [reply tests/test_ignite.py]: ignite versioning does not use characters in the minor number.
major.minor.patch.identifier

Comment (emcastillo) [reply tests/test_ignite.py]: The regexp used for semantic versioning also sees that version string as invalid
https://github.com/semver/semver/issues/232

Comment (niboshi) [reply tests/test_ignite.py]: So, does this function assume semver numbers?
If so, it should be documented in the implementation.
Also, is it reasonable to assume that? Is that stated in the ignite documentation?

Comment (niboshi) [reply tests/test_ignite.py]: Honestly I think we don't have to make this function's assumption very concrete by writing these tests.

Comment (emcastillo) [reply tests/test_ignite.py]: Decided to leave this as internal so tests are deleted.
Function has been further documented with the assumptions on ignite versioning system.

**Comment by niboshi** [comment]
```

2020-02-26 18:31:31.506580 STDOUT 1677] | =================================== FAILURES ===================================
-- | --
2020-02-26 18:31:31.506997 STDOUT 1677] | ____________________ test_link_as_torch_model_uninitialized ____________________
2020-02-26 18:31:31.507286 STDOUT 1677] |  
2020-02-26 18:31:31.507288 STDOUT 1677] | def test_link_as_torch_model_uninitialized():
2020-02-26 18:31:31.507289 STDOUT 1677] | # Uninitialized parameters are not supported
2020-02-26 18:31:31.507291 STDOUT 1677] | a_chainer_param = chainer.Parameter()
2020-02-26 18:31:31.507310 STDOUT 1677] |  
2020-02-26 18:31:31.507312 STDOUT 1677] | link = chainer.Link()
2020-02-26 18:31:31.507632 STDOUT 1677] | with link.init_scope():
2020-02-26 18:31:31.507635 STDOUT 1677] | link.a = a_chainer_param
2020-02-26 18:31:31.507636 STDOUT 1677] |  
2020-02-26 18:31:31.507637 STDOUT 1677] | with pytest.raises(TypeError):
2020-02-26 18:31:31.507650 STDOUT 1677] | >           torched = cpm.LinkAsTorchModel(link)
2020-02-26 18:31:31.507651 STDOUT 1677] |  
2020-02-26 18:31:31.507652 STDOUT 1677] | tests/test_parameter.py:235:
2020-02-26 18:31:31.507653 STDOUT 1677] | _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _
2020-02-26 18:31:31.507654 STDOUT 1677] |  
2020-02-26 18:31:31.508005 STDOUT 1677] | self = LinkAsTorchModel(), link = <chainer.link.Link object at 0x7ff3c3b116d8>
2020-02-26 18:31:31.508007 STDOUT 1677] |  
2020-02-26 18:31:31.508008 STDOUT 1677] | def __init__(self, link):
2020-02-26 18:31:31.508009 STDOUT 1677] | super().__init__()
2020-02-26 18:31:31.508010 STDOUT 1677] | uninitialized_params = [
2020-02-26 18:31:31.508011 STDOUT 1677] | n for n, p in sorted(_named_params(link)) if p.array is None]
2020-02-26 18:31:31.508012 STDOUT 1677] | if uninitialized_params:
2020-02-26 18:31:31.508308 STDOUT 1677] | raise RuntimeError(
2020-02-26 18:31:31.508310 STDOUT 1677] | 'Link with uninitialized parameters cannot be wrapped with '
2020-02-26 18:31:31.508311 STDOUT 1677] | 'LinkAsTorchModel. '
2020-02-26 18:31:31.508312 STDOUT 1677] | 'Please initialize parameters before wrapping, by feeding a '
2020-02-26 18:31:31.508549 STDOUT 1677] | 'dummy batch to the Chainer model, for example. '
2020-02-26 18:31:31.508551 STDOUT 1677] | 'Uninitialized params: [{}]'.format(
2020-02-26 18:31:31.508551 STDOUT 1677] | >                   ', '.join(repr(n) for n in uninitialized_params)))
2020-02-26 18:31:31.508789 STDOUT 1677] | E           RuntimeError: Link with uninitialized parameters cannot be wrapped with LinkAsTorchModel. Please initialize parameters before wrapping, by feeding a dummy batch to the Chainer model, for example. Uninitialized params: ['a']
2020-02-26 18:31:31.508793 STDOUT 1677] |  
2020-02-26 18:31:31.508794 STDOUT 1677] | chainer_pytorch_migration/parameter.py:43: RuntimeError
```

It doesn't seem related though.

**Comment by niboshi** [comment]
Fix for this failure: #18
